version: '3'

services:
  customer-api:
    build:
      context: ./src/services/customer/CustomerApi
      dockerfile: Dockerfile
    container_name: customerapi
    ports:
      - "80"
    volumes:
      - customerdata:/app/sqlite
    environment:
      - Kestrel__Endpoints__gRPC__Url=http://customer-api:5260
  
  ticket-api:
    build:
      context: ./src/services/ticket/TicketApi
      dockerfile: Dockerfile
    container_name: ticketapi
    ports:
      - "5052:80"
    volumes:
      - ticketdata:/app/sqlite

  receipt-api:
    build:
      context: ./src/services/receipt/ReceiptApi
      dockerfile: Dockerfile
    container_name: receiptapi
    ports:
      - "5003:80"
    volumes:
      - receiptdata:/app/sqlite

  apigateway:
    build:
      context: ./src/apigateways/ApiGateway
      dockerfile: Dockerfile
    container_name: apigateway
    ports:
      - "5058:80"
    env_file:
      - .env
    depends_on:
      - customer-api
      - ticket-api
      - receipt-api

volumes:
  customerdata:
  ticketdata:
  receiptdata: